nome : Windows - RustDesk

sobre :
  fluxo de trabalho_dispatch :

empregos :
  construir :
    nome : Comece a construir...
    executado : windows-mais recente
    minutos de tempo limite : 9999

    passos :
      - nome : Baixando e instalando Essentials
        execute : |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - nome : Faça login no AnyDesk
        execute : cmd /c show.bat

      - nome : Contador de tempo
        execute : python time.py
